SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[usp_xls_rendeles_update_insert]
AS


SET NOCOUNT ON

DECLARE @TÖLTŐ_ELÁJÁRÁS_NEVE VARCHAR(50) = 'XLS_RENDELÉS_UPDATE_INSERT - tárolteljárás'
DECLARE @BETÖLTŐ_SZEMÉLY VARCHAR(50) = SUSER_SNAME()
DECLARE @LOG_KULCS VARCHAR(50) = (SELECT [NewId] FROM GetNewID)

EXEC dbo.utils_log_info @TÖLTŐ_ELÁJÁRÁS_NEVE, 'Tárolt elindult', @BETÖLTŐ_SZEMÉLY, @LOG_KULCS;

BEGIN TRY 

	--xls
	DECLARE @XLS_RENDELÉS_KÓD NVARCHAR(255)
	DECLARE @XLS_ENTITÁS_KÓD NVARCHAR(255)
	DECLARE @XLS_MEGRENDELŐ_NEVE NVARCHAR(255)
	DECLARE @XLS_VÁLLALATI_CIKKSZÁM NVARCHAR(255)
	DECLARE @XLS_TERMÉK_NEVE NVARCHAR(255)
	DECLARE @XLS_RENDELT_MENNYISÉG NVARCHAR(255)
	DECLARE @XLS_ÁRA NVARCHAR(255)
	DECLARE @XLS_ÚJ_ÁR_AJÁNLAT_HUF NVARCHAR(255)
	DECLARE @XLS_ÚJ_ÁR_AJÁNLAT_EURO NVARCHAR(255)
	DECLARE @XLS_FIZETÉS_MÓDJA NVARCHAR(255)
	DECLARE @XLS_RENDELÉS_IDEJE NVARCHAR(255)
	DECLARE @XLS_MEGJEGYZÉS NVARCHAR(MAX)

	DECLARE @RENDELÉS_ID INT
	DECLARE @ENTITÁS_ID INT
	DECLARE @TERMÉK_ID INT 

	DECLARE RUI_CURSOR CURSOR FOR 
	SELECT
		TRIM(RENDELÉS_KÓD),
		TRIM(ENTITÁS_KÓD),
		TRIM(MEGRENDELŐ_NEVE),
		TRIM(VÁLLALATI_CIKKSZÁM),
		TRIM(TERMÉK_NEVE),
		TRIM(RENDELT_MENNYISÉG),
		TRIM(ÁRA),
		TRIM(ÚJ_ÁR_AJÁNLAT_HUF),
		TRIM(ÚJ_ÁR_AJÁNLAT_EURO),
		TRIM(FIZETÉS_MÓDJA),
		TRIM(RENDELÉS_IDEJE),
		TRIM(MEGJEGYZÉS)
	FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0','Excel 12.0;
	Database=C:\Excelek\Rendeles\Rendeles_felulet.xlsm;',
	'SELECT 
		RENDELÉS_KÓD,
		ENTITÁS_KÓD,
		MEGRENDELŐ_NEVE,
		VÁLLALATI_CIKKSZÁM,
		TERMÉK_NEVE,
		RENDELT_MENNYISÉG,
		ÁRA,
		ÚJ_ÁR_AJÁNLAT_HUF,
		ÚJ_ÁR_AJÁNLAT_EURO,
		FIZETÉS_MÓDJA,
		RENDELÉS_IDEJE,
		MEGJEGYZÉS
	FROM [RendelésFelvétel-Csere$]')

	OPEN RUI_CURSOR
	FETCH NEXT FROM RUI_CURSOR 
			  INTO 
				@XLS_RENDELÉS_KÓD,
				@XLS_ENTITÁS_KÓD,
				@XLS_MEGRENDELŐ_NEVE,
				@XLS_VÁLLALATI_CIKKSZÁM,
				@XLS_TERMÉK_NEVE,
				@XLS_RENDELT_MENNYISÉG,  
				@XLS_ÁRA,
				@XLS_ÚJ_ÁR_AJÁNLAT_HUF,
				@XLS_ÚJ_ÁR_AJÁNLAT_EURO,
				@XLS_FIZETÉS_MÓDJA,
				@XLS_RENDELÉS_IDEJE,
				@XLS_MEGJEGYZÉS

	WHILE @@FETCH_STATUS = 0  
		BEGIN  
				
				--fő objektumok
				SELECT @RENDELÉS_ID = RENDELÉS_ID FROM RENDELÉS WHERE RENDELÉS_KÓD = @XLS_RENDELÉS_KÓD
				SELECT @ENTITÁS_ID = ENTITÁS_ID FROM ENTITÁS WHERE ENTITÁS_KÓD = @XLS_ENTITÁS_KÓD
				SELECT @TERMÉK_ID = TERMÉK_ID FROM TERMÉK WHERE VÁLLALATI_CIKKSZÁM = @XLS_VÁLLALATI_CIKKSZÁM OR TERMÉK_NÉV = @XLS_TERMÉK_NEVE 
				
				
			--update begin 
			IF @XLS_RENDELÉS_KÓD IN (SELECT RENDELÉS_KÓD FROM RENDELÉS)
				BEGIN 
					IF @TERMÉK_ID <> (SELECT TERMÉK_ID FROM RENDELÉS_ÁR_AJÁNLAT WHERE RENDELÉS_ID = @RENDELÉS_ID)
						BEGIN 	
							UPDATE RENDELÉS_ÁR_AJÁNLAT
							SET TERMÉK_ID = @TERMÉK_ID
							WHERE RENDELÉS_ID = @RENDELÉS_ID
						END 
					IF @XLS_RENDELT_MENNYISÉG <> (SELECT RENDELT_MENNYISÉG FROM RENDELÉS_ÁR_AJÁNLAT WHERE RENDELÉS_ID = @RENDELÉS_ID)
						BEGIN 	
							UPDATE RENDELÉS_ÁR_AJÁNLAT
							SET RENDELT_MENNYISÉG = @XLS_RENDELT_MENNYISÉG
							WHERE RENDELÉS_ID = @RENDELÉS_ID
						END 	
					IF @XLS_ÚJ_ÁR_AJÁNLAT_HUF <> (SELECT ÁR_AJÁNLAT_HUF FROM RENDELÉS_ÁR_AJÁNLAT WHERE RENDELÉS_ID = @RENDELÉS_ID)
						BEGIN 
							UPDATE RENDELÉS_ÁR_AJÁNLAT
							SET RENDELT_MENNYISÉG = @XLS_RENDELT_MENNYISÉG
							WHERE RENDELÉS_ID = @RENDELÉS_ID
						END 	
					IF @XLS_ÚJ_ÁR_AJÁNLAT_EURO <> (SELECT ÁR_AJÁNLAT_EURO FROM RENDELÉS_ÁR_AJÁNLAT WHERE RENDELÉS_ID = @RENDELÉS_ID)
						BEGIN 
							UPDATE RENDELÉS_ÁR_AJÁNLAT
							SET RENDELT_MENNYISÉG = @XLS_RENDELT_MENNYISÉG
							WHERE RENDELÉS_ID = @RENDELÉS_ID
						END 	
					IF @XLS_FIZETÉS_MÓDJA <> (SELECT FIZETÉS_MÓDJA FROM RENDELÉS WHERE RENDELÉS_ID = @RENDELÉS_ID)
						BEGIN 
							UPDATE RENDELÉS
							SET FIZETÉS_MÓDJA = @XLS_FIZETÉS_MÓDJA
							WHERE RENDELÉS_ID = @RENDELÉS_ID
						END 	
					IF @XLS_MEGJEGYZÉS <> (SELECT MEGJEGYZÉS FROM RENDELÉS WHERE RENDELÉS_ID = @RENDELÉS_ID)
						BEGIN 
							UPDATE RENDELÉS
							SET MEGJEGYZÉS = @XLS_MEGJEGYZÉS
							WHERE RENDELÉS_ID = @RENDELÉS_ID
						END 
				END 	
			--insert begin
			ELSE 
				INSERT INTO RENDELÉS (ENTITÁS_ID, FIZETÉS_MÓDJA, RENDELÉS_IDEJE, MEGJEGYZÉS)
				VALUES(
						@ENTITÁS_ID,
						@XLS_FIZETÉS_MÓDJA,
						@XLS_RENDELÉS_IDEJE,
						@XLS_MEGJEGYZÉS
						)
						
				INSERT INTO RENDELÉS_ÁR_AJÁNLAT (RENDELÉS_ID, TERMÉK_ID, RENDELT_MENNYISÉG, ÁR_AJÁNLAT_HUF, ÁR_AJÁNLAT_EURO)
				VALUES(
						(SELECT MAX(RENDELÉS_ID) FROM RENDELÉS WHERE ENTITÁS_ID = @ENTITÁS_ID),
						@TERMÉK_ID,
						@XLS_RENDELT_MENNYISÉG,
						@XLS_ÚJ_ÁR_AJÁNLAT_HUF,
						@XLS_ÚJ_ÁR_AJÁNLAT_EURO
					)

			FETCH NEXT FROM RUI_CURSOR 
			  INTO 
				@XLS_RENDELÉS_KÓD,
				@XLS_ENTITÁS_KÓD,
				@XLS_MEGRENDELŐ_NEVE,
				@XLS_VÁLLALATI_CIKKSZÁM,
				@XLS_TERMÉK_NEVE,
				@XLS_RENDELT_MENNYISÉG,  
				@XLS_ÁRA,
				@XLS_ÚJ_ÁR_AJÁNLAT_HUF,
				@XLS_ÚJ_ÁR_AJÁNLAT_EURO,
				@XLS_FIZETÉS_MÓDJA,
				@XLS_RENDELÉS_IDEJE,
				@XLS_MEGJEGYZÉS
		END 

	CLOSE RUI_CURSOR
	DEALLOCATE RUI_CURSOR

END TRY 

BEGIN CATCH
		CLOSE RUI_CURSOR
		DEALLOCATE RUI_CURSOR

		-- Print error information. 
		PRINT 'Error ' + CONVERT(varchar(50), ERROR_NUMBER()) +
			  ', Severity ' + CONVERT(varchar(5), ERROR_SEVERITY()) +
			  ', State ' + CONVERT(varchar(5), ERROR_STATE()) + 
			  ', Procedure ' + ISNULL(ERROR_PROCEDURE(), '-') + 
			  ', Line ' + CONVERT(varchar(5), ERROR_LINE());
		PRINT ERROR_MESSAGE();

		DECLARE @SYS_ERROR_NUMBER varchar(50) = ERROR_NUMBER()
		DECLARE @SYS_ERROR_PROCEDURE varchar(50) = ISNULL(ERROR_PROCEDURE(), '-')
		DECLARE @SYS_ERROR_LINE varchar(50) = CONVERT(varchar(5), ERROR_LINE())
		DECLARE @SYS_ERROR_MESSAGE varchar(max) = ERROR_MESSAGE()
		
		EXEC dbo.utils_log_error @TÖLTŐ_ELÁJÁRÁS_NEVE, @SYS_ERROR_NUMBER, @SYS_ERROR_PROCEDURE, @SYS_ERROR_LINE, @SYS_ERROR_MESSAGE, @BETÖLTŐ_SZEMÉLY, @LOG_KULCS;

END CATCH;

EXEC dbo.utils_log_info @TÖLTŐ_ELÁJÁRÁS_NEVE, 'Tárolt befejeződött', @BETÖLTŐ_SZEMÉLY, @LOG_KULCS;
GO
